//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDN1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartenir
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Id_Navette { get; set; }
        public string Id_Client { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Navette Navette { get; set; }
    }
}
