//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDN1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Navette()
        {
            this.Appartenirs = new HashSet<Appartenir>();
        }
    
        public int Id { get; set; }
        public int Capacité { get; set; }
        public decimal Prix { get; set; }
        public bool Disponibilé { get; set; }
        public string Gamme { get; set; }
        public bool WIFI { get; set; }
        public bool TV { get; set; }
        public bool Climatisation { get; set; }
        public Nullable<int> Départ { get; set; }
        public Nullable<int> Arrivée { get; set; }
        public System.DateTime DateD { get; set; }
        public System.DateTime DateA { get; set; }
        public string Id_Entreprise { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appartenir> Appartenirs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Lieu Lieu { get; set; }
        public virtual Lieu Lieu1 { get; set; }
    }
}
